### PR TITLE
Fix crash when calling `minetest.log()` w/ one arg

### PR DESCRIPTION
**Pull request by Niklp09**
Trigger:
```lua
minetest.log("foo")
```

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
Thanks 👍
Which mod uses that format anyway?

**Comment by Niklp09** [comment]
>Which mod uses that format anyway?

Not sure, but for example I sometimes forget to add the level when debugging.

**Comment by debagos** [comment]
Since we don't do anything with the parameters, I suggest using 
```lua
function minetest.log(...)
	metric.inc()
	return old_log(...)
end
```

> Which mod uses that format anyway?

[3d_armor](https://github.com/minetest-mods/3d_armor/blob/467709c935a511912ee079cea352fc7c95b607e0/3d_armor/api.lua#L225) and [ts_doors](https://github.com/minetest-mods/ts_doors/blob/53f062ab720c0ac046edad3f019497b5952f69e1/init.lua#L90)
To be fair, in both cases it looks like a mistake and not done on purpose.

**Comment by BuckarooBanzay** [comment]
> Since we don't do anything with the parameters, I suggest using

Yeah, you are right :+1:  no idea why i specified the arguments :shrug:  https://github.com/minetest-monitoring/monitoring/issues/29

**Pull request merged**
